function fig = calibration_help()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load calibration_help
load calib_help_text

h0 = figure('Color',[0 0.85 0.85], ...
	'Colormap',mat0, ...
	'FileName','C:\plgui\mygui\calibration_help.m', ...
   'MenuBar','none', ...
   'numbertitle','off', ...
	'Name','Calibration Help', ...
	'PaperPosition',[0 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[100 200 560 450], ...
	'Tag','Calib_help_window', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'BackgroundColor',[0 .85 .85], ...
   'ForegroundColor',[0 0 .1], ...
	'ListboxTop',0, ...
   'Position',[.1 .85 .8 .1], ...
   'horizontalalignment','center', ...
   'fontsize',12,'fontweight','bold','fontname','helvetica',...
	'String',['VPR Calibration Steps'], ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.85 0.85], ...
	'Position',[0.05 0.1 .9 .8], ...
   'Style','listbox', ...
   'selectionhighlight','off', ...
   'String',calib_help_text, ...
   'fontsize',10, ...
	'Tag','Listbox Calib_help', ...
   'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.85 0.85], ...
	'Callback','close(gcbf)', ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[.8 .04  .1 .05], ...
	'String','Exit Help', ...
	'Tag','Pushbutton1 Quit', ...
	'TooltipString','Exit this window');

if nargout > 0, fig = h0; end
