sort_help_text=str2mat(...
'                                                                           ',...
'                                                                           ',...
' 1. Use this window to copy a subset of ROIs to the training ',...
'    directory (trrois).  (Note: this program creates a parallel path for   ',...
'    trrois, e.g., c:\data\cruise\trrois\vpr#\day#\hour#\). (You could also ',...
'    use windows explorer to create the trrois path and copy a subset of rois.) ',...
'    *********Note:  this parallel path for trrois is mandatory**********   ',...
'                                                                           ',...
'    Enter base path where rois are located and press Enter key, then select',...
'    cruise and VPR tow.   The number of rois in each day/hour will be      ',...
'    displayed in the left panel and the number of training rois will be    ',...
'    displayed in the right panel. Use the left mouse button to select rois ',...
'    to be copied from left panel (hold down control key or shift key to    ',...
'    select more than one hour).   Press the COPY button to copy selected   ',...
'    rois to trrois. (You also can enter a maximum number of rois per hour  ',...
'    to copy or type  all  to copy all rois in selected hours.)             ',...
'                                                                           ',...
' 2. Use an image thumbnail viewing program (e.g. Irfanview, Compupic, ',...
'    ThumbsPlus) or window explorer (in XP) to maually sort the rois in each',...
'    hour of TRROIS into the proper taxa folders. Use this thumbnail       ',...
'    viewing program or windows explorer to create the desired taxa folders ',...
'    within each hour folder in trrois.  The taxa folders must be inside the',...
'    hour folders. It is best to maually sort about 200 rois per taxon.      ');
                                                                           
    

save sort_help_text sort_help_text;

