main_help_text=str2mat(...
'                                                                           ',...
'                                                                           ',...
' This program is used to automatically identify VPR plankton images, time- ',...
' match the identifications with associated environmental variables, save   ',...
' the processed data, and plot the distributions.  The main steps include:  ',...
' calibration, focus detection, training the classifier, automatic plankton ',...
' identification, and saving/plotting the processed data.                   ',...
'                                                                           ',...
' Go through the steps shown in order.  Click on a step.  A brief           ',...
' description of that step is given in the help panel.  After selecting a   ',...
' step, click Apply, and a window will open for that step.  For each step,  ',...
' a full help window also is provided.                                      ',...
'                                                                           ',...
'                                                                           ',...
' NOTE:  Help bubbles are available for most objects and can be seen by     ',...
'            holding the mouse pointer over the object.                     ',...
'                                                                           ',...
'                                                                           ',...
'                                                                           ',...
'                                                                           ');
     

save main_help_text main_help_text;

