focus_help_text=str2mat(...
'                                                                           ',...
'                                                                           ',...
' 1. Double-click the desktop icon named AutoDeck.exe to start the program. ',...
' 2. Set output path for the ROI data using Options : Set Output Path       ',...
'    (i.e., c:\data\an9903\rois\vpr6). Create new vpr folders as needed.    ',...
'    ***Important:  You have to use the above format for the path, i.e., you',...
'    ***you must have a folder named ''rois'' and a folder for the vpr #,   ',...
'    ***The vpr # cannot have leading zeros and must be in the range 1-99.  ',...
'    ***The AutoDeck.exe program will automatically generate day and hour,  ',...
'    ***subfolders under the vpr# folder.                                   ',...
' 3. Julian day and hour will be automatically calculated and created.      ',...
' 4. Load the focus parameters determined during the calibration step.      ',...
' 5. Select Show ROIs to display captured ROIs on the screen.               ',...
' 6. Select Overlay ROIs to overlay captured ROIs on the screen.            ',...
' 7. Select Write ROIs to write ROI files to disk.                          ',...
' 8. Press Start Capture to toggle Start/Stop extraction of ROIs.           ');

save focus_help_text focus_help_text;
