plot_help_text=str2mat(...
'                                                                           ',...
' 1. Select drive from pull-down menu.  Then select folder.          ',...
' 2. Select cruise from pull-down menu.                                     ',...
' 3. Select radiobutton to activate VPR# pull down menu, for reading ctd.dat ',...
'    files.  Select VPR#                                                   ',...
' 4. Check/uncheck boxes to select/deselect plot types and save or load data.',...
' 5. Select replot interval from pull-down menu.  The plots will be updated ',...
'     at the interval selected.  Choose "only once" for one-time plotting.   ',...
' 6. If plankton plotting is chosen, a pull-down menu will appear for       ',...
'     selecting the appropriate classifier (created during "Step 3. Training ',...
'     the Computer").  Note that all classifiers are built in Step 3 and are ',...
'     show here, but only the one actually used in Classification (Step 4) ',...
'     should be chosen here.  ',...
' 7. Descriptions of plot types can be seen by holding the mouse cursor     ',...
'     over the plot type name.                                               ');

save plot_help_text plot_help_text;
