train_help_text=str2mat(...
'                                                                             ',...
'  This step is used to train the computer to identify plankton.              ',...
'                                                                             ',...
'  First, press "Copy Training ROIs" button to select and copy a subset of    ',...
'  ROIs to the training directory (trrois).  This creates a parallel directory',...
'  stucture identical to the rois one, with same vpr#, day, and hour, (e.g.   ',...
'  c:\data\trrois\vpr5\d183\h03). You can also use windows explorer to create ',...
'  the trrois folder and subfolders instead of the Copy Training ROIs feature.',...
'                                                                             ',...
'  Second, use an image thumbnail viewing program (e.g. Irfanview, Compupic,  ',...
'  ThumbsPlus) or Windows Explorer (in XP) to manually sort ROI files in each ',...
'  hour of TRROIS into the proper taxa folders in the same hour (create taxa  ',...
'  folders as needed), e.g.,c:\data\trrois\vpr5\d183\h03\copepods             ',...
'  *********This directory structure for trrois is mandatory.********         ',...
'                                                                             ',...
'  Third, press the "Build Classifier" button to select desired taxa, tows,   ',...
'  and classifier name and build the classifier.                              ',...
'                                                                             ');

save train_help_text train_help_text;

