classify_help_text=str2mat(...
'                                                                           ',...
'                                                                           ',...
' This step is used to extract features from rois and classify them using   ',...
' the classifier built in the previous training step.                       ',...
'                                                                           ',...
' Select VPR tow number and check the Classification and Feature Extraction ',...
' boxes (already checked by default).  Then choose the classifier type.     ',...
' Select SBF-NN for shape-based-features with neural network classifier,    ',...
' COM-SVM for cooccurrence matrix with support vector machine, or Dual for  ',...
' both classifiers used together. ROIs in the chosen hourly folders will be ',...
' automatically measured and classified and the results saved to files      ',...
' in the the autoid directory under taxa directories.  The automatic        ',...
' identification results are saved in hourly files in the aid subdirectory, ',...
' while the body size measurements are saved in hourly files in the aidmea  ',...
' subdirectory.                                                             ',...
'                                                                           ',...
' Enter the base path for the ROIs, the cruise, julian day, start hour, end ',...
' hour, classifer root name (without dual.mat svm.mat, nn.mat), and base   ',...
' path for the autoid results.  Entering an end hour that is greater than   ',...
' current time will cause the program to process ROIs as they are acquired. ',...
'                                                                           ',...
' After entering this information, press Start to run the classification    ',...
' program.                                                                  ');
     

save classify_help_text classify_help_text;

