function fig = main_help()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load main_help
load main_help_text

h0 = figure('Color',[0 0.85 0.85], ...
	'Colormap',mat0, ...
	'FileName','C:\plgui\mygui\main_help.m', ...
   'MenuBar','none', ...
   'numbertitle','off', ...
	'Name','Main Help', ...
	'PaperPosition',[18 180 576 432], ...
	'Units','normalized', ...
	'Position',[0.2480 0.3294 0.5215 0.4505], ...
	'Tag','Main_help_window', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
    'BackgroundColor',[0 .85 .85], ...
    'ForegroundColor',[0 0 .1], ...
	'ListboxTop',0, ...
    'Position',[.1 .85 .8 .1], ...
    'horizontalalignment','center', ...
    'fontunits','normalized','fontsize',.4,'fontweight','bold','fontname','helvetica',...
	'String',['Visual Plankton:  General Help'], ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.85 0.85], ...
	'Position',[.05 .1 .9 .8], ...
   'Style','listbox', ...
   'selectionhighlight','off', ...
   'String',main_help_text, ...
   'fontunits','normalized','fontsize',.048, ...
   'fontname','helvetica',...
	'Tag','Listbox Calib_help', ...
   'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0.85 0.85], ...
	'Callback','close(gcbf)', ...
	'fontunits','normalized','fontsize',.7,'FontWeight','normal', ...
	'ListboxTop',0, ...
	'Position',[.7 .025 .2 .05], ...
	'String','Exit Help', ...
	'Tag','Pushbutton1 Quit', ...
	'TooltipString','Exit this help window');

if nargout > 0, fig = h0; end
