function fig = plinit()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.
global MAT2 MAT3
load plinit;

h0 = figure(...
	'Colormap',mat0, ...
    'doublebuffer','on', ...
	'FileName','c:\plgui\mygui\plinit.m', ...
	'MenuBar','none', ...
   'numbertitle','off', ...
	'Name','Plankton Identification System', ...
	'PaperPosition',[18 180 576 432], ...
   'PaperUnits','points', ...
   'units','normalized',...
	'Position',[.22 .25 .6 .6], ...
	'Tag','Plankton Indentification System', ...
   'ToolBar','none',...
   'color',[0.2157 .6353 .6353]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
   'BackgroundColor',[0.2157 .6353 .6353], ...
   'ForegroundColor',[0 0 .1], ...
	'ListboxTop',0, ...
   'Position',[.05 .85 .9 .1], ...
   'horizontalalignment','center', ...
   'fontunits','normalized','fontsize',.35,'fontweight','bold','fontname','helvetica',...
	'String',['Visual Plankton:  The Video Plankton Recorder''s' char(10) '  Plankton' ...
      ' Identification and Visualization System'], ...
	'Style','text', ...
	'Tag','StaticText1');

h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Layer','top', ...
	'Position',[0.1175    0.4500    0.420    0.38], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 3300.5], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 2489.5], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
MAT3=imread('DAVPR.jpg');
h2 = image('Parent',h1, ...
	'CData',MAT3, ...
	'Tag','Axes1Image1', ...
 	'XData',[1 3300], ...
 	'YData',[1 2489]);
%     'UserData',['MAT3'],...
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[.9 1 1], ...
	'Position',[0.1    0.1167    0.520    0.2833], ...
	'String','', ...
	'Style','listbox', ...
   'fontunits','normalized','fontsize',.09,'fontweight','normal','fontname','helvetica',...
	'Tag','Listbox About', ...
	'TooltipString','This is a Help Window', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[.9 1 1], ...
	'Position',[0.6    0.57    0.32    0.16], ...
   'String',[str2mat('Step 1.  Calibration','Step 2.  Focus Detection',...
     'Step 3.  Training the Computer',...
     'Step 4.  Automatic Classification','Step 5.  View Results')],...
	'Style','listbox', ...
   'fontunits','normalized','fontsize',.15,'fontweight','normal','fontname','helvetica',...
	'Tag','Listbox Method', ...
	'TooltipString','Steps for using the Real-Time VPR System', ...
	'CreateFcn','plmaingui ShowAbout',...
	'Callback','plmaingui ShowAbout', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2157 .6353 .6353]*1.1, ...
	'ListboxTop',0, ...
	'Position',[0.6625    0.1167    0.1875    0.2833], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2157 .6353 .6353]*1.2, ...
	'ListboxTop',0, ...
   'fontunits','normalized','fontsize',.5,'fontweight','normal','fontname','helvetica',...
	'Position',[0.6875    0.3167    0.1375    0.0500], ...
	'String','Apply', ...
	'Tag','Pushbutton Apply', ...
	'Callback','plmaingui ApplyPLMAIN', ...
	'TooltipString','Apply the Step You Selected');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2157 .6353 .6353]*1.2, ...
	'ListboxTop',0, ...
   'fontunits','normalized','fontsize',.5,'fontweight','normal','fontname','helvetica',...
	'Position',[0.6875    0.2333    0.1375    0.0500], ...
	'String','Help', ...
	'Tag','Pushbutton Help', ...
	'Callback','main_help', ...
	'TooltipString','The big picture for the whole system');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.2157 .6353 .6353]*1.2, ...
	'Callback','close all;exit', ...
	'ListboxTop',0, ...
   'fontunits','normalized','fontsize',.5,'fontweight','normal','fontname','helvetica',...
	'Position',[0.6875    0.1500    0.1375    0.0500], ...
	'String','Exit', ...
	'Tag','Pushbutton Exit', ...
	'TooltipString','Exit the Program');
if nargout > 0, fig = h0; end

