function PLtrain_start

redgreenblue=[0.2157 .6353 .6353]*1.2;%let's make it lighter for this figure

h0 = figure('Units','normalized', ...
	'Color',[redgreenblue], ...
	'MenuBar','none', ...
	'Name','VPR:  Training the Computer', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
   'PaperUnits','points', ...
   'Position',[.5 .7  .4  .12], ...
	'Tag','PLextractFig', ...
	'ToolBar','none', ...
    'visible','on');
uicontrol('style','pushbutton','units','normalized','position',[.75 .2 .2 .3],'string','Exit','callback','close(gcbf)','backgroundcolor',redgreenblue,'fontsize',10,'fontweight','bold');
uicontrol('style','edit', 'horizontalalignment', 'left', 'fontunits','normalized','fontsize',.7, ...
    'units','normalized','position',[.1 .15 .6 .35], ...
    'tooltipstring',['Enter base path(s) to data (e.g., c:\data) and press Enter.' char(10) 'Separate multiple paths with space (e.g., c:\data d:\data)' char(10) 'If a specific cruise name is entered with path,' char(10) 'only that cruise will be used, e.g., c:\data\ast9903_cam2'], ...
    'callback','PLtrain','backgroundcolor','w');
uicontrol('style','text','units','normalized','position',[.1 .45 .6 .4],'string',['Enter Base Path(s)' char(10) 'for Training ROIs'],'backgroundcolor',redgreenblue,'fontsize',10,'fontweight','bold');
